//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> Shares { get; set; }
        public Nullable<int> Comments { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Update { get; set; }
        public string Content { get; set; }
        public string Tag { get; set; }
        public Nullable<int> Rates { get; set; }
        public string Slug { get; set; }
        public string ShortContent { get; set; }
    }
}
